/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Model.QLMuonTraModify;
import java.sql.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import Controler.SQLConnection;
import Model.QLMuonTra;
/**
 *
 * @author Vostro 3580
 */
public class QLMuonTraView extends javax.swing.JFrame {

    /**
     * Creates new form QLMuonTra
     */
    public QLMuonTraView() {
        initComponents();
        this.setTitle("Quản lý mượn trả_Lê Minh Nghĩa_ 20183960");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbDayM = new javax.swing.JComboBox<>();
        cbMonthM = new javax.swing.JComboBox<>();
        cbYearM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbDayT = new javax.swing.JComboBox<>();
        cbMonthT = new javax.swing.JComboBox<>();
        cbYearT = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTienCoc = new javax.swing.JTextField();
        comboxDG = new javax.swing.JComboBox<>();
        comboxTT = new javax.swing.JComboBox<>();
        txtMaMT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã mượn trả");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mã độc giả");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mã thủ thư");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Ngày mượn");

        cbDayM.setEditable(true);
        cbDayM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDayM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDayMActionPerformed(evt);
            }
        });

        cbMonthM.setEditable(true);
        cbMonthM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbMonthM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbMonthM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthMActionPerformed(evt);
            }
        });

        cbYearM.setEditable(true);
        cbYearM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbYearM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021" }));
        cbYearM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearMActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Ngày hẹn trả");

        cbDayT.setEditable(true);
        cbDayT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDayT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDayT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDayTActionPerformed(evt);
            }
        });

        cbMonthT.setEditable(true);
        cbMonthT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbMonthT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbMonthT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthTActionPerformed(evt);
            }
        });

        cbYearT.setEditable(true);
        cbYearT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbYearT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022" }));
        cbYearT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearTActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tiền cọc");

        txtTienCoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        comboxDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboxDG.setModel(new DefaultComboBoxModel(new QLMuonTraModify().comboxDG()));
        comboxDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxDGActionPerformed(evt);
            }
        });

        comboxTT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboxTT.setModel(new DefaultComboBoxModel(new QLMuonTraModify().comboxTT()));
        comboxTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTTActionPerformed(evt);
            }
        });

        txtMaMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMTActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("(đồng)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cbDayM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbMonthM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbYearM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(comboxDG, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(184, 184, 184)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboxTT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(120, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMaMT, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(304, 304, 304))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbDayT, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMonthT, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbYearT, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboxDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboxTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbDayM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMonthM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYearM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbDayT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMonthT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYearT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Quản lý mượn trả");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã mượn trả", "Mã độc giả", "Mã thủ thư", "Ngày mượn", "Ngày hẹn trả", "Tiền cọc"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuat.setText("Xuất file");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        btnSelect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelect.setText("Selected");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXuat)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(15, 15, 15))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnClear)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnXuat)
                    .addComponent(btnSelect))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMTActionPerformed

    private String dayM, monthM, yearM, dateM;
    private String dayT, monthT, yearT, dateT;
    private String dataDG=null, dataTT=null;
    private String header[]={"Mã mượn trả", "Mã độc giả", "Mã thủ thư", "Ngày mượn", "Ngày hẹn trả", "Tiền cọc"};
    private DefaultTableModel tblModel=new DefaultTableModel(header,0);
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        dateM=yearM+"-"+monthM+"-"+dayM;
        dateT=yearT+"-"+monthT+"-"+dayT;
        System.out.println(dateM);
        Connection conn=null;
        Statement st=null;
        ResultSet rs=null;
        try{
            Date d = Date.valueOf(dateM);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Ngày không tồn tại !");
            return;
        }
         try{
             Date d= Date.valueOf(dateT);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Ngày không tồn tại !");
            return;
        }
         if(txtMaMT.getText().length()==0 || txtTienCoc.getText().length()==0 || dateM==null || dateT==null){
            JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin !");
        }else{
            int ret=JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm mượn trả mới?", "Yes", JOptionPane.YES_NO_OPTION);
            if(ret!=JOptionPane.YES_OPTION){
                return;
            }
            ret=new QLMuonTraModify().Add(txtMaMT.getText(), dataDG, dataTT, dateM, dateT, txtTienCoc.getText());
            if(ret!=-1){
                JOptionPane.showMessageDialog(this, "Bạn đã thêm mới một sách thành công !");
               
            }
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbDayMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDayMActionPerformed
        // TODO add your handling code here:
        dayM=cbDayM.getSelectedItem().toString();
    }//GEN-LAST:event_cbDayMActionPerformed

    private void cbMonthMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthMActionPerformed
        // TODO add your handling code here:
        monthM=cbMonthM.getSelectedItem().toString();
    }//GEN-LAST:event_cbMonthMActionPerformed

    private void cbYearMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearMActionPerformed
        // TODO add your handling code here:
        yearM=cbYearM.getSelectedItem().toString();
    }//GEN-LAST:event_cbYearMActionPerformed

    private void cbDayTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDayTActionPerformed
        // TODO add your handling code here:
        dayT=cbDayT.getSelectedItem().toString();
    }//GEN-LAST:event_cbDayTActionPerformed

    private void cbMonthTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthTActionPerformed
        // TODO add your handling code here:
        monthT=cbMonthT.getSelectedItem().toString();
    }//GEN-LAST:event_cbMonthTActionPerformed

    private void cbYearTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearTActionPerformed
        // TODO add your handling code here:
        yearT=cbYearT.getSelectedItem().toString();
    }//GEN-LAST:event_cbYearTActionPerformed

    private void comboxDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxDGActionPerformed
        // TODO add your handling code here:
        dataDG=comboxDG.getSelectedItem().toString();
    }//GEN-LAST:event_comboxDGActionPerformed

    private void comboxTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxTTActionPerformed
        // TODO add your handling code here:
        dataTT=comboxTT.getSelectedItem().toString();
    }//GEN-LAST:event_comboxTTActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaMT.setText("");
        txtTienCoc.setText("");
        cbDayM.setSelectedItem("");
        cbMonthM.setSelectedItem("");
        cbYearM.setSelectedItem("");
        cbDayT.setSelectedItem("");
        cbMonthT.setSelectedItem("");
        cbYearT.setSelectedItem("");
        comboxDG.setSelectedItem("b101");
        comboxTT.setSelectedItem("tt101");
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int ret=JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa độc giả này?", "Yes", JOptionPane.YES_NO_OPTION);
        if(ret!=JOptionPane.YES_OPTION){
            return;
        }
        int selectedRow = table.getSelectedRow();
        if(selectedRow!=-1){
            String dataMa=tblModel.getValueAt(selectedRow, 0).toString();
            ret=new QLMuonTraModify().Delete(dataMa);
            if(ret!=-1){
                JOptionPane.showMessageDialog(this, "Bạn đã xóa mượn trả thành công !");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi, không thể xóa được mượn trả !");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st=null;
        ResultSet rs=null;
        try{
                    Vector data;
                    conn=new SQLConnection().Connect();
                    st=conn.createStatement();
                    rs=st.executeQuery("select * from Muontra_LeMinhNghia");
                    tblModel.setRowCount(0);
                    while(rs.next()){
                        data= new Vector();
                        data.add(rs.getString("MaMT_20183960"));
                        data.add(rs.getString("Ma_DG_20183960"));
                        data.add(rs.getString("Ma_TT_20183960"));
                        data.add(rs.getDate("Ngay_muon_20183960"));
                        data.add(rs.getDate("Ngay_hentra_20183960"));
                        data.add(rs.getFloat("Tiencoc_20183960"));
                        tblModel.addRow(data);
                        table.setModel(tblModel);
                    }
                    
                }catch(Exception ex){ex.printStackTrace();}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        int selected=table.getSelectedRow();
        if(selected!=-1){
        txtMaMT.setText(tblModel.getValueAt(selected, 0).toString());
        comboxDG.setSelectedItem(tblModel.getValueAt(selected, 1));
        comboxTT.setSelectedItem(tblModel.getValueAt(selected, 2));
        cbDayM.setSelectedItem(tblModel.getValueAt(selected, 3).toString().substring(8, 10));
        cbMonthM.setSelectedItem(tblModel.getValueAt(selected, 3).toString().substring(5, 7));
        cbYearM.setSelectedItem(tblModel.getValueAt(selected, 3).toString().substring(0, 4));
        cbDayT.setSelectedItem(tblModel.getValueAt(selected, 4).toString().substring(8, 10));
        cbMonthT.setSelectedItem(tblModel.getValueAt(selected, 4).toString().substring(5, 7));
        cbYearT.setSelectedItem(tblModel.getValueAt(selected, 4).toString().substring(0, 4));
        txtTienCoc.setText(tblModel.getValueAt(selected, 5).toString());
        btnEdit.setEnabled(true);
        btnAdd.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this, "Chưa có hàng nào được chọn !");
            return;
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        dateM=yearM+"-"+monthM+"-"+dayM;
        dateT=yearT+"-"+monthT+"-"+dayT;
        QLMuonTra mt= new QLMuonTra();
        mt.setMaMT(txtMaMT.getText());
        mt.setMaDG(dataDG);
        mt.setMaTT(dataTT);
        mt.setDateM(dateM);
        mt.setDateT(dateT);
        mt.setTienCoc(txtTienCoc.getText());
        int ret=new QLMuonTraModify().Edit(mt);
        if(ret==-1){
            JOptionPane.showMessageDialog(this, "Sửa đổi mượn trả không thành công !");
            return;
        }else{
            JOptionPane.showMessageDialog(this, "Sửa đổi mượn trả thành công !");
            return;
        }
    }//GEN-LAST:event_btnEditActionPerformed
    private void writeToExcel(){
        XSSFWorkBook a;
    }
    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLMuonTraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cbDayM;
    private javax.swing.JComboBox<String> cbDayT;
    private javax.swing.JComboBox<String> cbMonthM;
    private javax.swing.JComboBox<String> cbMonthT;
    private javax.swing.JComboBox<String> cbYearM;
    private javax.swing.JComboBox<String> cbYearT;
    private javax.swing.JComboBox<String> comboxDG;
    private javax.swing.JComboBox<String> comboxTT;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtMaMT;
    private javax.swing.JTextField txtTienCoc;
    // End of variables declaration//GEN-END:variables
}
